"""remove the foreing key from clients table

Revision ID: 1ee97600bfca
Revises: f86bfbcaede8
Create Date: 2021-12-15 11:51:18.280444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee97600bfca'
down_revision = 'f86bfbcaede8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_professional_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'professional_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('professional_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('clients_professional_id_fkey', 'clients', 'professional', ['professional_id'], ['id'])
    # ### end Alembic commands ###
