"""empty message

Revision ID: 251f3ad8cecb
Revises: bfc21049c586
Create Date: 2021-12-09 09:35:53.830306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251f3ad8cecb'
down_revision = 'bfc21049c586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deficiencies_client_id_fkey', 'deficiencies', type_='foreignkey')
    op.drop_column('deficiencies', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deficiencies', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deficiencies_client_id_fkey', 'deficiencies', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###
