"""empty message

Revision ID: 385374b68a32
Revises: 251f3ad8cecb
Create Date: 2021-12-09 09:39:19.059775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385374b68a32'
down_revision = '251f3ad8cecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deficiencies', sa.Column('disease_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deficiencies', 'disease_id')
    # ### end Alembic commands ###
