"""create all app

Revision ID: 48b21453ca4b
Revises: 
Create Date: 2021-12-13 15:14:01.391110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b21453ca4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deficiencies',
    sa.Column('deficiency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('deficiency_id')
    )
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('crm', sa.String(length=15), nullable=False),
    sa.Column('final_rating', sa.Float(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm'),
    sa.UniqueConstraint('email')
    )
    op.create_table('surgeries',
    sa.Column('surgery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('surgery_id')
    )
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weigth', sa.Float(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('professional_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deficiency_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('deficiency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['deficiency_id'], ['deficiencies.deficiency_id'], )
    )
    op.create_table('disease_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], )
    )
    op.create_table('food_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_name', sa.String(), nullable=True),
    sa.Column('pdf', sa.LargeBinary(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surgery_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('surgery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.surgery_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgery_client')
    op.drop_table('food_plan')
    op.drop_table('disease_client')
    op.drop_table('deficiency_client')
    op.drop_table('professional_rating')
    op.drop_table('clients')
    op.drop_table('surgeries')
    op.drop_table('professional')
    op.drop_table('diseases')
    op.drop_table('deficiencies')
    # ### end Alembic commands ###
