"""Creating 'food_plan' table

Revision ID: 5cba4dd54fcc
Revises: b0c6adbb631d
Create Date: 2021-12-09 16:12:11.307074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cba4dd54fcc'
down_revision = 'b0c6adbb631d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_plan')
    # ### end Alembic commands ###
