"""empty message

Revision ID: 904019fde854
Revises: 385374b68a32
Create Date: 2021-12-09 09:39:53.712408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904019fde854'
down_revision = '385374b68a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deficiencies', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deficiencies', 'clients', ['client_id'], ['client_id'])
    op.drop_column('deficiencies', 'disease_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deficiencies', sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deficiencies', type_='foreignkey')
    op.drop_column('deficiencies', 'client_id')
    # ### end Alembic commands ###
