"""alteracoes

Revision ID: 9506b09c14b8
Revises: 8d71b7393055
Create Date: 2021-12-09 18:48:06.464533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9506b09c14b8'
down_revision = '8d71b7393055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professional', sa.Column('last_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professional', 'last_name')
    # ### end Alembic commands ###
