"""empty message

Revision ID: a15866c7ff27
Revises: d0e8185de129
Create Date: 2021-12-09 10:04:58.309706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15866c7ff27'
down_revision = 'd0e8185de129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deficiencies_client_id_fkey', 'deficiencies', type_='foreignkey')
    op.drop_column('deficiencies', 'client_id')
    op.drop_constraint('diseases_client_id_fkey', 'diseases', type_='foreignkey')
    op.drop_column('diseases', 'client_id')
    op.drop_constraint('surgeries_client_id_fkey', 'surgeries', type_='foreignkey')
    op.drop_column('surgeries', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surgeries', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('surgeries_client_id_fkey', 'surgeries', 'clients', ['client_id'], ['client_id'])
    op.add_column('diseases', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('diseases_client_id_fkey', 'diseases', 'clients', ['client_id'], ['client_id'])
    op.add_column('deficiencies', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deficiencies_client_id_fkey', 'deficiencies', 'clients', ['client_id'], ['client_id'])
    # ### end Alembic commands ###
