"""empty message

Revision ID: b0c6adbb631d
Revises: a15866c7ff27
Create Date: 2021-12-09 11:39:14.343250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0c6adbb631d'
down_revision = 'a15866c7ff27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deficiency_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('deficiency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['deficiency_id'], ['deficiencies.deficiency_id'], )
    )
    op.create_table('disease_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], )
    )
    op.create_table('surgery_client',
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('surgery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.surgery_id'], )
    )
    op.drop_table('infirmities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infirmities',
    sa.Column('infirmity_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deficiency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('surgery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], name='infirmities_client_id_fkey'),
    sa.ForeignKeyConstraint(['deficiency_id'], ['deficiencies.deficiency_id'], name='infirmities_deficiency_id_fkey'),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name='infirmities_disease_id_fkey'),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.surgery_id'], name='infirmities_surgery_id_fkey'),
    sa.PrimaryKeyConstraint('infirmity_id', name='infirmities_pkey')
    )
    op.drop_table('surgery_client')
    op.drop_table('disease_client')
    op.drop_table('deficiency_client')
    # ### end Alembic commands ###
