"""initial migration

Revision ID: bfc21049c586
Revises: 
Create Date: 2021-12-08 21:40:31.257535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc21049c586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('last_name', sa.String(length=63), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=63), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weigth', sa.Float(), nullable=False),
    sa.Column('imc', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deficiencies',
    sa.Column('deficiency_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('deficiency_id')
    )
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('disease_id')
    )
    op.create_table('surgeries',
    sa.Column('surgery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=31), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('surgery_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surgeries')
    op.drop_table('diseases')
    op.drop_table('deficiencies')
    op.drop_table('clients')
    # ### end Alembic commands ###
