"""empty message

Revision ID: d0e8185de129
Revises: 904019fde854
Create Date: 2021-12-09 10:03:56.491270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e8185de129'
down_revision = '904019fde854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infirmities',
    sa.Column('infirmity_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('deficiency_id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('surgery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.ForeignKeyConstraint(['deficiency_id'], ['deficiencies.deficiency_id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], ),
    sa.ForeignKeyConstraint(['surgery_id'], ['surgeries.surgery_id'], ),
    sa.PrimaryKeyConstraint('infirmity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infirmities')
    # ### end Alembic commands ###
