"""adjusted models for 'cascade'

Revision ID: d66f5633eb9c
Revises: 1ee97600bfca
Create Date: 2021-12-16 11:28:30.243664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66f5633eb9c'
down_revision = '1ee97600bfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calendar_professional_id_fkey', 'calendar', type_='foreignkey')
    op.drop_constraint('calendar_client_id_fkey', 'calendar', type_='foreignkey')
    op.create_foreign_key(None, 'calendar', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'calendar', 'professional', ['professional_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('food_plan_client_id_fkey', 'food_plan', type_='foreignkey')
    op.create_foreign_key(None, 'food_plan', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('professional_rating_professional_id_fkey', 'professional_rating', type_='foreignkey')
    op.create_foreign_key(None, 'professional_rating', 'professional', ['professional_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professional_rating', type_='foreignkey')
    op.create_foreign_key('professional_rating_professional_id_fkey', 'professional_rating', 'professional', ['professional_id'], ['id'])
    op.drop_constraint(None, 'food_plan', type_='foreignkey')
    op.create_foreign_key('food_plan_client_id_fkey', 'food_plan', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    op.drop_constraint(None, 'calendar', type_='foreignkey')
    op.create_foreign_key('calendar_client_id_fkey', 'calendar', 'clients', ['client_id'], ['id'])
    op.create_foreign_key('calendar_professional_id_fkey', 'calendar', 'professional', ['professional_id'], ['id'])
    # ### end Alembic commands ###
